language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: "qRFCZh9pkgHguGAYeTC+acl7sReS7/wcEugIZvjT9nzahAwPXlFaRzhEa/P+Z/ycmAMZjR3fUHPuHR3ajgirHNC4A7MbK6Oelij8yLHIPFfxf3hdC5IUZKrWuzG5614tPU0NpsmR4EVTG8RnUpdOaVLYCmeAXZ0Y4wbtStzdHOU="
    - REPO="git@github.com:appleboy/js-video-player"
after_success: build/after_success.sh
